INSERT INTO subject (name) VALUES
    ('Animals');

INSERT INTO word (name, hint, subject_id) VALUES
('Elephant', 'A large mammal with a trunk', 1),
('Tiger', 'A big cat with orange and black stripes', 1),
('Dolphin', 'An intelligent marine mammal', 1),
('Eagle', 'A bird of prey with sharp vision', 1),
('Panda', 'A bear that loves bamboo', 1),
('Kangaroo', 'A marsupial that hops', 1),
('Cheetah', 'The fastest land animal', 1),
('Penguin', 'A flightless bird that swims', 1),
('Wolf', 'A wild canine that howls', 1),
('Bear', 'A large mammal with thick fur', 1),
('Zebra', 'An animal with black and white stripes', 1),
('Giraffe', 'The tallest animal in the world', 1),
('Lion', 'Known as the king of the jungle', 1),
('Otter', 'A playful aquatic mammal', 1),
('Flamingo', 'A pink bird that stands on one leg', 1),
('Shark', 'A predator of the sea', 1),
('Turtle', 'A reptile with a hard shell', 1),
('Rabbit', 'A small mammal that hops', 1),
('Crocodile', 'A reptile with a powerful bite', 1),
('Peacock', 'A bird with vibrant tail feathers', 1),
('Octopus', 'A sea creature with eight arms', 1),
('Fox', 'A cunning animal with a bushy tail', 1),
('Snail', 'A small creature with a spiral shell', 1),
('Butterfly', 'An insect with colorful wings', 1),
('Whale', 'The largest animal in the ocean', 1),
('Antelope', 'A swift and graceful herbivore', 1),
('Monkey', 'A primate that loves bananas', 1),
('Parrot', 'A colorful bird that can mimic speech', 1),
('Seal', 'A marine mammal that claps', 1),
('Hedgehog', 'A small mammal with spines', 1),
('Raccoon', 'A nocturnal animal with a masked face', 1),
('Bat', 'The only flying mammal', 1),
('Frog', 'An amphibian that leaps', 1),
('Deer', 'An animal with antlers', 1),
('Moose', 'A large deer with broad antlers', 1),
('Camel', 'An animal with humps on its back', 1),
('Sloth', 'The slowest mammal on earth', 1),
('Sparrow', 'A small and common bird', 1),
('Lobster', 'A crustacean with claws', 1),
('Crab', 'A crustacean with a sideways walk', 1),
('Ostrich', 'The largest bird in the world', 1),
('Chimpanzee', 'A highly intelligent primate', 1),
('Alligator', 'A reptile similar to a crocodile', 1),
('Seahorse', 'A tiny marine creature shaped like a horse', 1),
('Porcupine', 'An animal with quills', 1),
('Salamander', 'An amphibian with a long tail', 1),
('Skunk', 'An animal known for its smell', 1),
('Starfish', 'A sea creature with five arms', 1),
('Koala', 'A marsupial that eats eucalyptus leaves', 1),
('Lizard', 'A reptile with scaly skin', 1);

