
-- Subjects
INSERT INTO subject (id, name) VALUES
    (1, 'Animals'),
    (2, 'Sport'),
    (3, 'Programming'),
    (4, 'Music');

-- Animals
INSERT INTO word (name, hint, subject_id) VALUES
      ('Elephant', 'Large and known for its memory.', 1),
      ('Cheetah', 'Speed defines this predator.', 1),
      ('Dolphin', 'Graceful in the ocean and intelligent.', 1),
      ('Kangaroo', 'Moves by leaping with a pouch.', 1),
      ('Penguin', 'Flightless and dressed for formal occasions.', 1),
      ('Owl', 'A nocturnal symbol of wisdom.', 1),
      ('Giraffe', 'A giant that reaches for the skies.', 1),
      ('Panda', 'Black and white, a symbol of conservation.', 1),
      ('Eagle', 'A symbol of strength soaring high.', 1),
      ('Tiger', 'Striped and stealthy in the wild.', 1),
      ('Lion', 'Known as the ruler of its domain.', 1),
      ('Shark', 'A predator known for its fin.', 1),
      ('Bat', 'Navigator of the night with echolocation.', 1),
      ('Camel', 'Adapted for arid travels.', 1),
      ('Peacock', 'Renowned for its vivid display.', 1),
      ('Sloth', 'Moves at an unhurried pace.', 1),
      ('Wolf', 'A pack animal known for its howl.', 1),
      ('Frog', 'A jumper often found near water.', 1),
      ('Rabbit', 'Quick and a symbol of abundance.', 1),
      ('Fox', 'Clever and often elusive.', 1),
      ('Bear', 'Mighty and hibernates in the cold.', 1),
      ('Deer', 'Graceful and quick on its feet.', 1),
      ('Zebra', 'Striped and part of the plains.', 1),
      ('Horse', 'A companion of speed and power.', 1),
      ('Octopus', 'An expert of camouflage underwater.', 1),
      ('Whale', 'A giant that sings through the seas.', 1),
      ('Raccoon', 'A masked bandit of the night.', 1),
      ('Crocodile', 'An ancient predator of rivers.', 1),
      ('Snake', 'A silent slitherer.', 1),
      ('Parrot', 'Colorful and mimics sounds.', 1),
      ('Turtle', 'Carries its home wherever it goes.', 1),
      ('Bee', 'A small pollinator with a sting.', 1),
      ('Ant', 'A small worker of large colonies.', 1),
      ('Leopard', 'A spotted predator of stealth.', 1),
      ('Chimpanzee', 'A close relative known for intelligence.', 1),
      ('Flamingo', 'A wader with pink elegance.', 1),
      ('Hedgehog', 'A prickly creature that curls up.', 1),
      ('Koala', 'Eucalyptus is its main diet.', 1),
      ('Penguin', 'A diver in icy waters.', 1),
      ('Lemur', 'A jumper with a long, striped tail.', 1),
      ('Armadillo', 'A little armored digger.', 1),
      ('Porcupine', 'Defended by sharp quills.', 1),
      ('Seal', 'An aquatic mammal that basks on rocks.', 1),
      ('Cobra', 'A hooded snake with a fearsome gaze.', 1),
      ('Otter', 'Playful and floats on its back.', 1),
      ('Jellyfish', 'A drifting creature with stingers.', 1),
      ('Moose', 'A towering grazer of northern forests.', 1),
      ('Hyena', 'Known for its distinctive laugh.', 1),
      ('Gazelle', 'A swift and graceful plains animal.', 1);

-- Sports
INSERT INTO word (name, hint, subject_id) VALUES
      ('Soccer', 'A team sport involving a goal and teamwork.', 2),
      ('Basketball', 'A sport where height is often an advantage.', 2),
      ('Tennis', 'Played with precision and a net in between.', 2),
      ('Baseball', 'A game with innings and diamond-shaped paths.', 2),
      ('Volleyball', 'A sport where hands meet airborne tactics.', 2),
      ('Cricket', 'A pitch-centered game with overs and runs.', 2),
      ('Hockey', 'A fast-paced sport often involving a puck.', 2),
      ('Golf', 'A game where the fewest strokes wins.', 2),
      ('Swimming', 'Racing through lanes without touching ground.', 2),
      ('Boxing', 'A strategic clash of fists and endurance.', 2),
      ('Badminton', 'A feathered projectile meets quick reflexes.', 2),
      ('Rugby', 'A high-contact contest of an oval object.', 2),
      ('Table Tennis', 'A duel on a small surface with quick reactions.', 2),
      ('Wrestling', 'A struggle to outmaneuver and pin an opponent.', 2),
      ('Archery', 'Precision tools launched to distant marks.', 2),
      ('Cycling', 'Endurance and speed propelled by wheels.', 2),
      ('Skating', 'Fluid motion requiring balance and agility.', 2),
      ('Rowing', 'Synchronized strength propelling across water.', 2),
      ('Diving', 'Aerial artistry culminating in a splash.', 2),
      ('Gymnastics', 'Controlled artistry with flips and apparatus.', 2),
      ('Skiing', 'Downhill movement powered by gravity and skill.', 2),
      ('Snowboarding', 'Graceful motion over frozen terrain.', 2),
      ('Surfing', 'Mastering the power of moving aquatic crests.', 2),
      ('Martial Arts', 'Disciplined movement blending defense and offense.', 2),
      ('Karate', 'Focused strikes honed with discipline.', 2),
      ('Judo', 'Technique-driven grapples and calculated movements.', 2),
      ('Taekwondo', 'Dynamic movements emphasizing power and reach.', 2),
      ('Fencing', 'A dance of tactics with sharpened precision.', 2),
      ('Weightlifting', 'Force against gravity in a single motion.', 2),
      ('Track and Field', 'Pure athleticism showcased in many forms.', 2),
      ('Pole Vault', 'Ascending heights with the aid of leverage.', 2),
      ('Shot Put', 'A test of strength and perfect angles.', 2),
      ('Discus', 'Momentum channeled into distant flight.', 2),
      ('High Jump', 'Elevating with finesse over a set mark.', 2),
      ('Triple Jump', 'Three distinct movements reaching one distance.', 2),
      ('Long Jump', 'Flight through the air after a sprint.', 2),
      ('Crossfit', 'Strength, speed, and stamina merged in chaos.', 2),
      ('Climbing', 'Vertical motion through grips and footholds.', 2),
      ('Parkour', 'Adaptable motion through urban landscapes.', 2),
      ('Skateboarding', 'A balancing act on wheels and gravity.', 2),
      ('Esports', 'Virtual arenas of skill and strategy.', 2),
      ('Chess', 'A battlefield of intellect and foresight.', 2),
      ('Darts', 'An exercise in precision and steady hands.', 2),
      ('Bowling', 'A calculated roll to topple targets.', 2),
      ('Horse Racing', 'Speed and synergy between two beings.', 2),
      ('Equestrian', 'Elegance and precision on horseback.', 2),
      ('Snooker', 'Precision-guided play with colored spheres.', 2),
      ('Sailing', 'Harnessing nature’s force for momentum.', 2),
      ('Canoeing', 'Streamlined travel through water channels.', 2);

-- Programming
INSERT INTO word (name, hint, subject_id) VALUES
      ('Python', 'I’m a snake, but I help code instead of bite.', 3),
      ('JavaScript', 'I bring web pages to life, though my name deceives.', 3),
      ('HTML', 'I’m the skeleton of every webpage you see.', 3),
      ('CSS', 'I style and dress up the web’s bones.', 3),
      ('SQL', 'I speak in tables, rows, and queries.', 3),
      ('C++', 'I build on a letter, adding power and complexity.', 3),
      ('Java', 'I brew logic, but I’m not a cup of coffee.', 3),
      ('Ruby', 'I sparkle in simplicity for developers.', 3),
      ('PHP', 'I serve the web with scripts on demand.', 3),
      ('Kotlin', 'I modernize Android with jet-powered code.', 3),
      ('Swift', 'I fly fast for Apple’s creations.', 3),
      ('TypeScript', 'I add structure to the chaos of scripts.', 3),
      ('Rust', 'I prevent memory leaks with safety in mind.', 3),
      ('Go', 'I’m efficient, simple, and made to race.', 3),
      ('Perl', 'I’m a pearl of scripting flexibility.', 3),
      ('Shell', 'I command the system with a few lines.', 3),
      ('Django', 'I’m a framework that’s full-stack but lightweight.', 3),
      ('Flask', 'I’m minimal, but I serve Python’s web.', 3),
      ('React', 'I build interfaces by breaking them into parts.', 3),
      ('Vue', 'I give you a clear perspective for front-end design.', 3),
      ('Node.js', 'I bring JavaScript to the server’s table.', 3),
      ('Angular', 'I architect the web with a firm structure.', 3),
      ('GraphQL', 'I query APIs with precision and less noise.', 3),
      ('PostgreSQL', 'I’m a powerful elephant in the database room.', 3),
      ('MongoDB', 'I store data in JSON-like documents.', 3),
      ('Git', 'I track changes in your code’s history.', 3),
      ('Docker', 'I contain worlds of applications in small packages.', 3),
      ('Kubernetes', 'I orchestrate containers with precision.', 3),
      ('Jenkins', 'I automate builds like a faithful butler.', 3),
      ('Terraform', 'I shape infrastructure like a sculptor.', 3),
      ('Ansible', 'I automate tasks with no agents involved.', 3),
      ('Linux', 'I’m open, free, and power servers globally.', 3),
      ('Bash', 'I’m a shell that speaks in scripts.', 3),
      ('Vim', 'I’m an editor that many love but few master.', 3),
      ('Emacs', 'I’m an editor, a shell, and even a game console.', 3),
      ('TensorFlow', 'I help machines learn from data.', 3),
      ('PyTorch', 'I light the way for AI experiments.', 3),
      ('NumPy', 'I handle numbers in arrays with ease.', 3),
      ('Pandas', 'I process data tables in Python.', 3),
      ('Matplotlib', 'I plot pictures from data points.', 3),
      ('Jupyter', 'I host notebooks for code and more.', 3),
      ('Bootstrap', 'I simplify styles with grids and pre-made classes.', 3),
      ('Webpack', 'I bundle files for the modern web.', 3),
      ('JSON', 'I’m lightweight and easy for machines to read.', 3),
      ('XML', 'I’m older but still tag along for data.', 3),
      ('YAML', 'I configure with indentation in mind.', 3),
      ('Regex', 'I match patterns like a language of its own.', 3),
      ('Assembly', 'I’m the closest you’ll get to speaking to a machine.', 3);

-- Music
INSERT INTO word (name, hint, subject_id) VALUES
    ('Piano', 'Large keyboard instrument.', 4),
    ('Guitar', 'Stringed instrument, played by strumming.', 4),
    ('Drums', 'Percussion instrument played with sticks or hands.', 4),
    ('Violin', 'String instrument played with a bow.', 4),
    ('Trumpet', 'Brass instrument with valves.', 4),
    ('Saxophone', 'Brass wind instrument used in jazz.', 4),
    ('Flute', 'Woodwind instrument played by blowing across a hole.', 4),
    ('Cello', 'Large string instrument with a deep sound.', 4),
    ('Bass', 'Low-pitched string instrument.', 4),
    ('Clarinet', 'Woodwind instrument with a single reed.', 4),
    ('Harp', 'Stringed instrument played by plucking.', 4),
    ('Oboe', 'Double-reed woodwind instrument.', 4),
    ('Timpani', 'Kettledrums, used in orchestras.', 4),
    ('Accordion', 'Instrument with bellows and keys/buttons.', 4),
    ('Xylophone', 'Percussion instrument with wooden bars.', 4),
    ('Tambourine', 'Small percussion instrument with jingles.', 4),
    ('Maracas', 'Rattles used as percussion instruments.', 4),
    ('Keyboard', 'Electronic musical instrument with keys.', 4),
    ('Flugelhorn', 'Brass instrument with a mellow sound.', 4),
    ('Mandolin', 'Stringed instrument with a rounded body.', 4),
    ('Banjo', 'Stringed instrument with a drum-like body.', 4),
    ('Fiddle', 'Another name for a violin in folk music.', 4),
    ('Acoustic', 'Musical instrument that doesn’t need amplification.', 4),
    ('Electric', 'Instrument that requires electronic amplification.', 4),
    ('Chord', 'Two or more notes played together.', 4),
    ('Scale', 'Sequence of notes in a specific order.', 4),
    ('Rhythm', 'Pattern of beats in music.', 4),
    ('Melody', 'A sequence of notes that form a tune.', 4),
    ('Harmony', 'Combination of notes played together.', 4),
    ('Key', 'The tonal center of a piece of music.', 4),
    ('Tempo', 'The speed of a piece of music.', 4),
    ('Cadence', 'The ending of a musical phrase.', 4),
    ('Dynamics', 'Variation in loudness of music.', 4),
    ('Articulation', 'How notes are played or sung.', 4),
    ('Interval', 'Distance between two musical notes.', 4),
    ('Octave', 'Doubling or halving the frequency of a note.', 4),
    ('Chorus', 'The repeated part of a song.', 4),
    ('Verse', 'Part of a song with lyrics that tell a story.', 4),
    ('Bridge', 'Contrasting section in a song.', 4),
    ('Song', 'A musical composition with lyrics.', 4),
    ('Opera', 'A dramatic work combining singing and music.', 4),
    ('Symphony', 'Large orchestral composition, usually in four movements.', 4),
    ('Concerto', 'Composition for a soloist and orchestra.', 4),
    ('Sonata', 'A composition for one or more instruments, typically three or four movements.', 4),
    ('Jazz', 'Genre of music known for improvisation.', 4),
    ('Blues', 'Genre of music with a melancholic tone.', 4),
    ('Rock', 'Genre with electric guitars and strong rhythms.', 4),
    ('Classical', 'Western music tradition from the 18th-19th centuries.', 4),
    ('Pop', 'Mainstream music with catchy melodies.', 4),
    ('Hip Hop', 'Music with rhythmic speech and beats.', 4),
    ('Reggae', 'Jamaican music with a steady beat.', 4),
    ('Folk', 'Traditional music from a specific culture.', 4),
    ('Electronic', 'Music produced using electronic devices.', 4),
    ('Soundtrack', 'Music accompanying a film or show.', 4);
