
-- Subjects
INSERT INTO subject (id, name) VALUES
    (1, 'Animals'),
    (2, 'Sport'),
    (3, 'Programming'),
    (4, 'Music'),
    (5, 'Movies'),
    (6, 'Universe');

-- Animals
INSERT INTO word (name, hint, subject_id) VALUES
      ('Elephant', 'Large and known for its memory.', 1),
      ('Cheetah', 'Speed defines this predator.', 1),
      ('Dolphin', 'Graceful in the ocean and intelligent.', 1),
      ('Kangaroo', 'Moves by leaping with a pouch.', 1),
      ('Owl', 'A nocturnal symbol of wisdom.', 1),
      ('Giraffe', 'A giant that reaches for the skies.', 1),
      ('Panda', 'Black and white, a symbol of conservation.', 1),
      ('Eagle', 'A symbol of strength soaring high.', 1),
      ('Tiger', 'Striped and stealthy in the wild.', 1),
      ('Lion', 'Known as the ruler of its domain.', 1),
      ('Shark', 'A predator known for its fin.', 1),
      ('Bat', 'Navigator of the night with echolocation.', 1),
      ('Camel', 'Adapted for arid travels.', 1),
      ('Peacock', 'Renowned for its vivid display.', 1),
      ('Sloth', 'Moves at an unhurried pace.', 1),
      ('Wolf', 'A pack animal known for its howl.', 1),
      ('Frog', 'A jumper often found near water.', 1),
      ('Rabbit', 'Quick and a symbol of abundance.', 1),
      ('Fox', 'Clever and often elusive.', 1),
      ('Bear', 'Mighty and hibernates in the cold.', 1),
      ('Deer', 'Graceful and quick on its feet.', 1),
      ('Zebra', 'Striped and part of the plains.', 1),
      ('Horse', 'A companion of speed and power.', 1),
      ('Octopus', 'An expert of camouflage underwater.', 1),
      ('Whale', 'A giant that sings through the seas.', 1),
      ('Raccoon', 'A masked bandit of the night.', 1),
      ('Crocodile', 'An ancient predator of rivers.', 1),
      ('Snake', 'A silent slitherer.', 1),
      ('Parrot', 'Colorful and mimics sounds.', 1),
      ('Turtle', 'Carries its home wherever it goes.', 1),
      ('Bee', 'A small pollinator with a sting.', 1),
      ('Ant', 'A small worker of large colonies.', 1),
      ('Leopard', 'A spotted predator of stealth.', 1),
      ('Chimpanzee', 'A close relative known for intelligence.', 1),
      ('Flamingo', 'A wader with pink elegance.', 1),
      ('Hedgehog', 'A prickly creature that curls up.', 1),
      ('Koala', 'Eucalyptus is its main diet.', 1),
      ('Penguin', 'A diver in icy waters.', 1),
      ('Lemur', 'A jumper with a long, striped tail.', 1),
      ('Armadillo', 'A little armored digger.', 1),
      ('Porcupine', 'Defended by sharp quills.', 1),
      ('Seal', 'An aquatic mammal that basks on rocks.', 1),
      ('Cobra', 'A hooded snake with a fearsome gaze.', 1),
      ('Otter', 'Playful and floats on its back.', 1),
      ('Jellyfish', 'A drifting creature with stingers.', 1),
      ('Moose', 'A towering grazer of northern forests.', 1),
      ('Hyena', 'Known for its distinctive laugh.', 1),
      ('Gazelle', 'A swift and graceful plains animal.', 1);

-- Sports
INSERT INTO word (name, hint, subject_id) VALUES
      ('Soccer', 'A team sport involving a goal and teamwork.', 2),
      ('Basketball', 'A sport where height is often an advantage.', 2),
      ('Tennis', 'Played with precision and a net in between.', 2),
      ('Baseball', 'A game with innings and diamond-shaped paths.', 2),
      ('Volleyball', 'A sport where hands meet airborne tactics.', 2),
      ('Cricket', 'A pitch-centered game with overs and runs.', 2),
      ('Hockey', 'A fast-paced sport often involving a puck.', 2),
      ('Golf', 'A game where the fewest strokes wins.', 2),
      ('Swimming', 'Racing through lanes without touching ground.', 2),
      ('Boxing', 'A strategic clash of fists and endurance.', 2),
      ('Badminton', 'A feathered projectile meets quick reflexes.', 2),
      ('Rugby', 'A high-contact contest of an oval object.', 2),
      ('Wrestling', 'A struggle to outmaneuver and pin an opponent.', 2),
      ('Archery', 'Precision tools launched to distant marks.', 2),
      ('Cycling', 'Endurance and speed propelled by wheels.', 2),
      ('Skating', 'Fluid motion requiring balance and agility.', 2),
      ('Rowing', 'Synchronized strength propelling across water.', 2),
      ('Diving', 'Aerial artistry culminating in a splash.', 2),
      ('Gymnastics', 'Controlled artistry with flips and apparatus.', 2),
      ('Skiing', 'Downhill movement powered by gravity and skill.', 2),
      ('Snowboarding', 'Graceful motion over frozen terrain.', 2),
      ('Surfing', 'Mastering the power of moving aquatic crests.', 2),
      ('Karate', 'Focused strikes honed with discipline.', 2),
      ('Judo', 'Technique-driven grapples and calculated movements.', 2),
      ('Taekwondo', 'Dynamic movements emphasizing power and reach.', 2),
      ('Fencing', 'A dance of tactics with sharpened precision.', 2),
      ('Weightlifting', 'Force against gravity in a single motion.', 2),
      ('Discus', 'Momentum channeled into distant flight.', 2),
      ('Crossfit', 'Strength, speed, and stamina merged in chaos.', 2),
      ('Climbing', 'Vertical motion through grips and footholds.', 2),
      ('Parkour', 'Adaptable motion through urban landscapes.', 2),
      ('Skateboarding', 'A balancing act on wheels and gravity.', 2),
      ('Esports', 'Virtual arenas of skill and strategy.', 2),
      ('Chess', 'A battlefield of intellect and foresight.', 2),
      ('Darts', 'An exercise in precision and steady hands.', 2),
      ('Bowling', 'A calculated roll to topple targets.', 2),
      ('Equestrian', 'Elegance and precision on horseback.', 2),
      ('Snooker', 'Precision-guided play with colored spheres.', 2),
      ('Sailing', 'Harnessing nature’s force for momentum.', 2),
      ('Canoeing', 'Streamlined travel through water channels.', 2);

-- Programming
INSERT INTO word (name, hint, subject_id) VALUES
    ('Python', 'I’m a snake, but I code.', 3),
    ('JavaScript', 'I bring websites to life.', 3),
    ('HTML', 'I’m the structure of a webpage.', 3),
    ('CSS', 'I style the web.', 3),
    ('SQL', 'I use tables, rows, and queries.', 3),
    ('C++', 'I build on C with more power.', 3),
    ('Java', 'I brew logic, not coffee.', 3),
    ('Ruby', 'I’m simple and sparkly for developers.', 3),
    ('PHP', 'I run web scripts.', 3),
    ('Kotlin', 'I power Android with modern code.', 3),
    ('Swift', 'I’m fast for Apple development.', 3),
    ('TypeScript', 'I add structure to JavaScript.', 3),
    ('Rust', 'I prevent memory leaks with safety.', 3),
    ('Go', 'I’m fast, simple, and efficient.', 3),
    ('Perl', 'I’m flexible in scripting.', 3),
    ('Shell', 'I command the system via scripts.', 3),
    ('Django', 'I’m a full-stack, lightweight framework.', 3),
    ('Flask', 'I’m minimal for Python web apps.', 3),
    ('React', 'I build UIs with components.', 3),
    ('Vue', 'I offer a clean front-end framework.', 3),
    ('Node.js', 'I run JavaScript on servers.', 3),
    ('Angular', 'I structure web apps with precision.', 3),
    ('GraphQL', 'I query APIs efficiently.', 3),
    ('PostgreSQL', 'I’m a powerful relational database.', 3),
    ('MongoDB', 'I store data in JSON-like documents.', 3),
    ('Git', 'I track code changes.', 3),
    ('Docker', 'I containerize applications.', 3),
    ('Kubernetes', 'I manage containers.', 3),
    ('Jenkins', 'I automate builds and deployments.', 3),
    ('Terraform', 'I shape cloud infrastructure.', 3),
    ('Ansible', 'I automate tasks without agents.', 3),
    ('Linux', 'I power servers and are open-source.', 3),
    ('Bash', 'I’m a shell scripting language.', 3),
    ('Vim', 'I’m an editor for power users.', 3),
    ('Emacs', 'I’m an editor and more.', 3),
    ('TensorFlow', 'I help machines learn from data.', 3),
    ('PyTorch', 'I assist with AI research and experiments.', 3),
    ('NumPy', 'I handle arrays and numbers.', 3),
    ('Pandas', 'I process data in tables.', 3),
    ('Matplotlib', 'I visualize data with graphs.', 3),
    ('Jupyter', 'I host interactive coding notebooks.', 3),
    ('Bootstrap', 'I simplify web design with grids.', 3),
    ('Webpack', 'I bundle files for the web.', 3),
    ('JSON', 'I’m a lightweight data format.', 3),
    ('XML', 'I tag data for transfer.', 3),
    ('YAML', 'I use indentation for configuration.', 3),
    ('Regex', 'I match patterns in text.', 3),
    ('Assembly', 'I’m close to machine language.', 3);

-- Music
INSERT INTO word (name, hint, subject_id) VALUES
    ('Piano', 'Large keyboard instrument.', 4),
    ('Guitar', 'Stringed instrument, strummed.', 4),
    ('Drums', 'Percussion, played with sticks or hands.', 4),
    ('Violin', 'String instrument, played with a bow.', 4),
    ('Trumpet', 'Brass instrument with valves.', 4),
    ('Saxophone', 'Brass wind, used in jazz.', 4),
    ('Flute', 'Woodwind, played by blowing.', 4),
    ('Cello', 'Large string, deep sound.', 4),
    ('Bass', 'Low-pitched string instrument.', 4),
    ('Clarinet', 'Woodwind, single reed.', 4),
    ('Harp', 'String instrument, plucked.', 4),
    ('Oboe', 'Double-reed woodwind.', 4),
    ('Timpani', 'Kettledrums in orchestras.', 4),
    ('Accordion', 'Bellows with keys/buttons.', 4),
    ('Xylophone', 'Percussion with wooden bars.', 4),
    ('Tambourine', 'Percussion with jingles.', 4),
    ('Maracas', 'Rattle percussion instrument.', 4),
    ('Keyboard', 'Electronic instrument with keys.', 4),
    ('Flugelhorn', 'Brass with mellow sound.', 4),
    ('Mandolin', 'Stringed, rounded body.', 4),
    ('Banjo', 'Stringed with drum-like body.', 4),
    ('Fiddle', 'Violin in folk music.', 4),
    ('Acoustic', 'Instrument without amplification.', 4),
    ('Electric', 'Requires electronic amplification.', 4),
    ('Chord', 'Two or more notes together.', 4),
    ('Scale', 'Sequence of ordered notes.', 4),
    ('Rhythm', 'Pattern of beats.', 4),
    ('Melody', 'A tune of notes.', 4),
    ('Harmony', 'Combined notes played together.', 4),
    ('Key', 'Tonality of a piece of music.', 4),
    ('Tempo', 'Speed of music.', 4),
    ('Cadence', 'End of a musical phrase.', 4),
    ('Dynamics', 'Loudness variation in music.', 4),
    ('Articulation', 'How notes are played or sung.', 4),
    ('Interval', 'Distance between notes.', 4),
    ('Octave', 'Doubling/halving note frequency.', 4),
    ('Chorus', 'Repeated part of a song.', 4),
    ('Verse', 'Storytelling part of a song.', 4),
    ('Bridge', 'Contrasting song section.', 4),
    ('Song', 'Musical composition with lyrics.', 4),
    ('Opera', 'Singing and music drama.', 4),
    ('Symphony', 'Large orchestral composition.', 4),
    ('Concerto', 'Soloist with orchestra.', 4),
    ('Sonata', 'Instrumental composition, multiple movements.', 4),
    ('Jazz', 'Improvisational music genre.', 4),
    ('Blues', 'Melancholic music genre.', 4),
    ('Rock', 'Electric guitars, strong rhythms.', 4),
    ('Classical', '18th-19th century Western music.', 4),
    ('Pop', 'Mainstream, catchy music.', 4),
    ('Reggae', 'Jamaican music, steady beat.', 4),
    ('Folk', 'Traditional culture music.', 4),
    ('Electronic', 'Music via electronic devices.', 4),
    ('Soundtrack', 'Music for film or show.', 4);

-- Movies
INSERT INTO word (name, hint, subject_id) VALUES
    ('Inception', 'Dreams within dreams.', 5),
    ('Titanic', 'A doomed ship.', 5),
    ('Avatar', 'Aliens on Pandora.', 5),
    ('Gladiator', 'A Roman fighter.', 5),
    ('Jaws', 'A deadly shark.', 5),
    ('Frozen', 'Magic ice powers.', 5),
    ('Memento', 'Memory loss.', 5),
    ('Alien', 'Horror in space.', 5),
    ('Coco', 'Day of the Dead.', 5),
    ('Dune', 'Desert planet.', 5),
    ('Trolls', 'Singing creatures.', 5),
    ('Moana', 'Ocean adventure.', 5),
    ('Rocky', 'A boxer rises.', 5),
    ('Up', 'House with balloons.', 5),
    ('Cars', 'Talking vehicles.', 5),
    ('Ratatouille', 'Cooking rat.', 5),
    ('Dumbo', 'Flying elephant.', 5),
    ('Hercules', 'Greek hero.', 5),
    ('Aladdin', 'Magic lamp.', 5),
    ('Shrek', 'An ogre’s quest.', 5),
    ('Brave', 'A Scottish archer.', 5),
    ('Coraline', 'Alternate world.', 5),
    ('Soul', 'Musician’s journey.', 5),
    ('Bolt', 'Superdog hero.', 5),
    ('Rango', 'A desert sheriff.', 5),
    ('Zootopia', 'Animal city.', 5),
    ('Beetlejuice', 'Ghostly mischief.', 5),
    ('Cinderella', 'Glass slipper.', 5),
    ('Braveheart', 'Scottish freedom.', 5),
    ('Selma', 'Civil rights march.', 5),
    ('Amadeus', 'Mozart’s life.', 5),
    ('Parasite', 'Class divide.', 5),
    ('Minions', 'Yellow helpers.', 5),
    ('Divergent', 'Faction system.', 5),
    ('Tangled', 'Lost princess.', 5),
    ('Tarzan', 'Jungle man.', 5),
    ('Bambi', 'Deer’s life.', 5),
    ('Hamlet', 'A Danish prince.', 5),
    ('Rashomon', 'Different perspectives.', 5),
    ('Gandhi', 'Peace advocate.', 5),
    ('Lincoln', 'Civil War leader.', 5),
    ('Patton', 'WWII general.', 5),
    ('Amélie', 'Whimsical life.', 5),
    ('Glory', 'Civil War heroes.', 5),
    ('Metropolis', 'Futuristic city.', 5),
    ('Spartacus', 'Slave rebellion.', 5),
    ('Argo', 'Hostage rescue.', 5),
    ('Chicago', 'Murder and jazz.', 5);



-- Universe
INSERT INTO word (name, hint, subject_id) VALUES
    ('Star', 'I shine from afar.', 6),
    ('Planet', 'I orbit a star.', 6),
    ('Galaxy', 'A group of stars.', 6),
    ('Nebula', 'A star-forming gas cloud.', 6),
    ('Asteroid', 'A rocky space traveler.', 6),
    ('Comet', 'I leave a fiery trail.', 6),
    ('Supernova', 'A star’s explosive end.', 6),
    ('Quasar', 'A bright black hole beacon.', 6),
    ('Pulsar', 'A spinning star with signals.', 6),
    ('Constellation', 'Stars in a pattern.', 6),
    ('Meteor', 'I burn in the atmosphere.', 6),
    ('Moon', 'I orbit Earth.', 6),
    ('Aurora', 'Colorful polar lights.', 6),
    ('Exoplanet', 'I orbit another star.', 6),
    ('Andromeda', 'Our neighboring galaxy.', 6),
    ('Orbit', 'A path shaped by gravity.', 6),
    ('Eclipse', 'One body hides another.', 6),
    ('Cosmos', 'All that exists.', 6),
    ('Gravity', 'The force that pulls us down.', 6),
    ('Hubble', 'A telescope for deep space.', 6),
    ('Telescope', 'I see distant stars.', 6),
    ('Satellite', 'I orbit planets.', 6),
    ('Singularity', 'Infinite density point.', 6),
    ('Photon', 'I carry light.', 6),
    ('Magnetar', 'A star with intense magnetism.', 6),
    ('Voyager', 'A spacecraft to the stars.', 6),
    ('Horizon', 'Where the sky meets Earth.', 6),
    ('Supercluster', 'A group of galaxies.', 6),
    ('Multiverse', 'Many worlds beyond ours.', 6);

